### ISSUE TITLE
Use the serializer component to prepare DTO object and validate with the validator component

### ISSUE THREAD

**Issue by avionwd** [Killakan789/testcode#1]
Create a DTO class to collect data from the request and use the serializer component to deserialize JSON data from the request into a new DTO object.

Create validation rules for the DTO object and use the validator component to validate the received data from a client ((!) do not believe a client, always validate all received data).

https://github.com/Killakan789/testcode/blob/e01970fa7a10f62ef1d28b91ba4dd20554ddf8c3/symfony/src/Controller/CustomerController.php#L29-L38

**Comment by avionwd** [comment]
### Validator usage

You use `ValidatorInterface $validator` in the several actions inside your controller, so to prevent duplication of the same autowired service you can use composition and inject the required service via `__constructor()`:

```PHP
public function __construct(ValidatorInterface $validator)
{
    $this->validator = $validator;
}
```

### Serializer

You should use configured and initialized serialize from the DI and inject it into the controller to use for logic operations. 
So, your code is not suitable:

https://github.com/Killakan789/testcode/blob/7f91962efde02243a1ffb6dd3b4070cb56c0b376/symfony/src/Controller/CustomerController.php#L38-L41

Read the documentation https://symfony.com/doc/current/serializer.html

----
Another suggestion, to be more productive I propose to use pull requests with reference to issues. If will be more informative and constructive, I can add comments to your new code before it will be merged into master.

**Comment by avionwd** [comment]
Also, DTO (Data Transfer Object) is the most preferred way to create validation rules, validate and use them in the next steps.

https://github.com/Killakan789/testcode/blob/7f91962efde02243a1ffb6dd3b4070cb56c0b376/symfony/src/Controller/CustomerController.php#L43-L59

This code could be transformed into:
```php
$dto = $this->serializer->deserialize($request->getContents(), CustomerDTO::class, 'json');
$errors = $this->validator->validate($dto);
if (count($errors)) {
   // thow an exception or create reponse object with required structure
}
// complete the logic as everything is ok
```

**Comment by Killakan789** [comment]
okay,will do that

**Comment by Killakan789** [comment]
eZBranch : changed serializer initialisation through injection into constructor (also removed unnecessary code lines),changed adding method and updating method (using DTO class to validate data and passed validated data to create customer or update one)

**Comment by avionwd** [comment]
Validation will no work at lines and their analogies:
https://github.com/Killakan789/testcode/blob/83440c03b1caea3267399dba33008d9328c78ce4/symfony/src/Controller/CustomerController.php#L37-L39

You have no configured validation rules for the created DTO class. Take a look at the documentation https://symfony.com/doc/current/validation.html#the-basics-of-validation

**Comment by Killakan789** [comment]
merged branches after a commit (added validation rules for the properties such as id,firstName,lastName,email,phoneNumber) checked routes with DTO validation - seems working 

  /**
     * @Assert\Type (
     *     type="string",
     *     message = "The firstName property '{{ value }}' should be a string type",
     * )
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    public $firstName;
    /**
     * @Assert\Type("string")
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    public $lastName;
    /**
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email.",
     * )
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    public $email;
    /**
     * @Assert\Type("string")
     * @Assert\Length(min = 8, max = 20, minMessage = "minimal length is 8 numbers in a string", maxMessage = "maximal length is 20 numbers in a string")
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    public $phoneNumber;
