### ISSUE TITLE
Vendor folder shouldn't be in the repository

### ISSUE THREAD

**Issue by avionwd** [Killakan789/testcode#2]
The vendor folder contains a lot of files and settings suitable for the local environment. They useless in the repository and always will lead to significant disk usage and cost (if repo service is paid).

To keep the requirements and settings int the repo these files should be committed:
- composer.json
- composer.lock (exact libraries versions that were used during development)

**Comment by Killakan789** [comment]
removed vendor  from repository in the root folder as well as in the symfony folder by adding .gitignore file with excluding it and removed by console from repository
