### ISSUE TITLE
Secure API with the auth

### ISSUE THREAD

**Issue by avionwd** [Killakan789/testcode#7]
Use [Security](https://symfony.com/doc/current/security.html) component to secure API endpoints for customer with `basic_auth`.

Users can have roles:
- ROLE_ADMIN
- ROME_MANAGER
- ROLE_USER

An only authenticated user with roles ROLE_ADMIM, ROLE_MANAGER can have access to the customer data.

---
Useful documentation:
- https://symfony.com/doc/current/security.html
- https://symfony.com/doc/current/components/security/authorization.html

**Comment by Killakan789** [comment]
created authentication and registration form also added user roles after authentication (if its manager you can view customers or certain customer if its admin then you can have access to create\update\delete) - checked only web version will work on api from postman
